### ISSUE TITLE
How to edit the minecraft icon

### ISSUE THREAD

**Issue by CrowBaldeYT** [egold555/MCP-Snippets#3]

**Comment by TheKodeToad** [comment]
In `net.minecraft.client.Minecraft` find the method called `setWindowIcon`.

Replace
```java
inputstream = this.mcDefaultResourcePack.getInputStreamAssets(new ResourceLocation("icons/icon_16x16.png"));
inputstream1 = this.mcDefaultResourcePack.getInputStreamAssets(new ResourceLocation("icons/icon_32x32.png"));
```
with
```java
inputstream = this.getClass().getResourceAsStream("/client_icons/icon_16x16.png");
inputstream1 = this.getClass().getResourceAsStream("/client_icons/icon_32x32.png");
```

Copy a 32x32 icon to "Client Project Folder/src/minecraft/client_icons/icon_32x32.png".
Scale the image to 16x16 and save it to "Client Project Folder/src/minecraft/client_icons/icon_16x16.png".

Next time the client is started, it will have the new icon.

**Comment by Creative-Difficulty** [comment]
`setWindowIcon` is ca. at line 685!

**Comment by Creative-Difficulty** [comment]
in `Minecraft.java`

**Comment by CrowBaldeYT** [comment]
Thanks, i replied bit late lol

**Comment by magnemint** [comment]
It doesnt work, it loads the default java logo instead. I dont know if its because of my icons or because of the file location.

**Comment by Creative-Difficulty** [comment]
show example

**Comment by DaniboOrg** [comment]
nvm found out the problem i put the icons in the wrong directory

**Comment by KalixYT** [comment]
where's the directory?

**Comment by KalixYT** [comment]
im probably dumb

**Comment by TheKodeToad** [comment]
Oh my god, why is GitHub emailing me for this still
